# Generated by Django 5.2.12 on 2026-03-28 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_video_name', models.CharField(max_length=255)),
                ('user_video_name', models.CharField(max_length=255)),
                ('overall_score', models.FloatField()),
                ('grade', models.CharField(max_length=5)),
                ('most_inconsistent_joint', models.CharField(max_length=50)),
                ('most_inconsistent_phase', models.CharField(max_length=50)),
                ('feedback_json', models.TextField()),
                ('joint_scores_json', models.TextField()),
                ('chart_score_card', models.TextField()),
                ('chart_radar', models.TextField()),
                ('chart_joint_bars', models.TextField()),
                ('chart_angle_curves', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_data', models.BinaryField(blank=True, null=True)),
                ('n_samples', models.IntegerField(default=0)),
                ('n_made', models.IntegerField(default=0)),
                ('n_missed', models.IntegerField(default=0)),
                ('cv_accuracy', models.FloatField(blank=True, null=True)),
                ('model_type', models.CharField(blank=True, max_length=50)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('training_status', models.CharField(default='idle', max_length=20)),
                ('training_message', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('label', models.IntegerField()),
                ('features_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
