# Generated by Django 5.2.12 on 2026-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('style_notes', models.TextField(blank=True)),
                ('sequence_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
