# Generated by Django 5.2.12 on 2026-04-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot_analyzer', '0002_playertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertemplate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos/'),
        ),
    ]
