# Generated by Django 5.2.12 on 2026-04-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot_analyzer', '0003_playertemplate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='phase_scores_json',
            field=models.TextField(default='[]'),
        ),
    ]
