# Generated by Django 5.2.12 on 2026-04-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot_analyzer', '0004_add_phase_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmodel',
            name='reference_sequence_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingsample',
            name='sequence_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
