# Generated by Django 5.2.12 on 2026-04-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shot_analyzer', '0005_add_sequence_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysissession',
            name='most_inconsistent_phase',
        ),
        migrations.RemoveField(
            model_name='analysissession',
            name='phase_scores_json',
        ),
    ]
